### ISSUE TITLE
About encoding issue of "unzip" command on colab

### ISSUE THREAD

**Issue by ling199104** [AI-FREE-Team/Traditional-Chinese-Handwriting-Dataset#1]
Simply using "-O" modifier in the command.

In the original line:
`!unzip  /content/handwritting_data_all/all_data.zip -d "/content"`
Use the following line instead:
`!unzip -O big5 /content/handwritting_data_all/all_data.zip -d "/content"` 

See more description by using 
`!unzip --help`

**Comment by chenkenanalytic** [comment]
Thanks for the help!
